FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS BASE
COPY dist /app
WORKDIR /app
EXPOSE 80/tcp
ENV ASPNETCORE_URLS http://+:80
CMD ["pwsh", "waitScript.ps1"]
ENTRYPOINT ["dotnet", "BlazorMovieApp.dll"]
